### PR TITLE
Fixing grammer

### PR DESCRIPTION
**Pull request by kentcdodds**
Could be:

> ... your questions haven't already...

Or

> ... your question hasn't already...

### CODE REVIEW

**Comment by sindresorhus** [comment]
Let's go with `hasn't`.

**Comment by kentcdodds** [comment]
Will do!

**Comment by sindresorhus** [comment]
Fyi, no need to open a new PR. Just amend the commit locally and force push to the remote branch to update the existing PR.

**Comment by kentcdodds** [comment]
Yeah, I know, but I was bothered by the multiple branches that I had in the repo because of github's editor so I pulled down the repo and started everything from scratch :-) I think I may have a little ocd...

**Pull request closed without merging**
